WebApplication/Areas/Admin/Controllers/CategoryController.cs
using Model.Dao;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        // GET: Admin/Category
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreateNewProductCategory()
        {
            return PartialView("CreateProductCategory");
        }

        [HttpPost]
        public ActionResult CreateProductCategory(ProductCategory category)
        {
            if (ModelState.IsValid)
            {
                var dao = new CategoryDao();
                if (dao.CheckProductCategoryName(category.Name))
                {
                    ModelState.AddModelError("", "Duplicate product category name!");
                }

                else
                {
                    long id = dao.Insert(category);
                    if (id > 0)
                    {
                        TempData["SuccessMessage"] = "Product Category " + category.Name + " Created Successfully!";
                        return Json(true, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            return PartialView("CreateProductCategory", category);
        }

    }
}

WebApplication/Controllers/ProductController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult ProductCategory()
        {
            var model = new ProductCategoryDao().ListAll();
            return PartialView(model);
        }

        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            },JsonRequestBehavior.AllowGet) ;  
        }

        public ActionResult Search(string keyword, int page = 1, int pageSize = 1)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public ActionResult Category(long cateId, int page = 1, int pageSize = 1)
        {
            var category = new CategoryDao().ViewDetail(cateId);
            ViewBag.Category = category;
            int totalRecord = 0;
            var model = new ProductDao().ListByCategoryId(cateId, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public ActionResult Detail(long id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.Category = new ProductCategoryDao().ViewDetail(product.CategoryID);
            ViewBag.RelatedProducts = new ProductDao().ListRelatedProducts(id);
            return View(product);
        }
    }
}

WebApplication/Areas/Admin/Views/Category/Create.cshtml
@model Model.EF.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}


@section header{
    <h2>ADD PRODUCT CATEGORY</h2>
    <hr />
    @using (Html.BeginForm("Create", "Category", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false, "", new { @class = "text-danger" });

        <div class="form-horizontal">

            <div class="form-group" style="width : 1000px">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, @style = "width:200px" })
            </div>

            <div class="form-group" style="width : 1000px">
                @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control" }, @style = "width:200px" })
            </div>

            <div class="form-group" style="width : 1000px">
                @Html.LabelFor(model => model.MetaDescriptions, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(model => model.MetaDescriptions, new { htmlAttributes = new { @class = "form-control" }, @style = "width:200px" })
            </div>

            <div class="form-group" style="width : 1000px">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Status)

            </div>

            <div class="form-group">
                <div class="col-md-offset-3 col-md-auto">
                    <input class="btn btn-primary" type="submit" value="Create" />
                </div>
            </div>
        </div>
    }

    <div style="margin-left:8px">
        @Html.ActionLink("Back to List", "Index", "Product")
    </div>
}

WebApplication/Areas/Admin/Views/Category/CreateProductCategory.cshtml
@model Model.EF.ProductCategory

<div class="modal-header">
    <span>ADD PRODUCT CATEGORY</span>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
</div>
<div class="modal-body">
    @using (Html.BeginForm("CreateProductCategory", "Category", FormMethod.Post, new { @id = "myForm", @name = "productCategoryForm" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(false, "", new { @class = "text-danger" });

        <div class="form-group" style="width : 1000px">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" }, @style = "width:250px" })
        </div>

        <div class="form-group" style="width : 1000px">
            @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control" }, @style = "width:250px" })
        </div>

        <div class="form-group" style="width : 1000px">
            @Html.LabelFor(model => model.MetaDescriptions, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.TextBoxFor(model => model.MetaDescriptions, new { htmlAttributes = new { @class = "form-control" }, @style = "width:250px" })
        </div>

        <div class="form-group" style="width : 1000px">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Status)
        </div>

        <div class="modal-footer">
            &nbsp;
            <button type="button" onclick="createProductCategory()" class="btn btn-primary">Create</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
    }
</div>